name: MyCash
main: mycash.Main
author: maru
version: "1.0.1"
api: ["1.0.0"]

permissions:
 mycash.*:
  default: false
  children:
   mycash.commands.*:
    default: false
    children:
     mycash.commands.cash.*:
      default: true
      children:
       mycash.commands.cash:
       mycash.commands.cash.mycash:
       mycash.commands.cash.charge:
       mycash.commands.cash.history:
     mycash.commands.managecash.*:
      default: OP
      children:
       mycash.commands.managecash:
       mycash.commands.managecash.see:
       mycash.commands.managecash.give:
       mycash.commands.managecash.take:
       mycash.commands.managecash.chargelist:
       mycash.commands.managecash.check:
       mycash.commands.managecash.givepermission:
