name: MyCash
main: mycash.Main
author: maru
version: "1.0.0"
api: ["1.0.0"]

commands:
 캐쉬:
  usage: "/캐쉬 <내캐쉬|충전|내역>"
  description: "캐쉬를 충전하거나 내역을 확인합니다."
  permission: mycash.commands.cash.*
 캐쉬관리:
  usage: "/캐쉬관리 <보기|주기|뺏기|충전목록|확인|권한주기>"
  description: "캐쉬를 관리합니다."
  permission: mycash.commands.managecash.*

permissions:
 mycash.*:
  default: false
  children:
   mycash.commands.*:
    default: false
    children:
     mycash.commands.cash.*:
      default: true
      children:
       mycash.commands.cash.mycash:
       mycash.commands.cash.charge:
       mycash.commands.cash.history:
     mycash.commands.managecash.*:
      default: OP
      children:
       mycash.commands.managecash.see:
       mycash.commands.managecash.give:
       mycash.commands.managecash.take:
       mycash.commands.managecash.chargelist:
       mycash.commands.managecash.check:
       mycash.commands.managecash.givepermission:
